FROM python:3.10-slim

WORKDIR /app

# Copy requirements and install libraries
COPY requirements_streamlit.txt .
RUN pip install -r requirements_streamlit.txt

# Copy all frontend app code
COPY . .

# Expose the port Streamlit runs on
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "streamlit_app.py"]